

def build(bld):
    bld.DefineGem(
        #includes
        includes = [ bld.Path('Code/CryEngine/CryAction') ],

        debug_win_linkflags = [ '/VERBOSE' ],

        #library
        lib = [ 'Live2DCubismCore' ],
        
        #library paths
        #windows
        win_debug_libpath = [ bld.Path('Gems/Cubism3/3rdParty/develop/windows/x86_64') ],
        win_release_libpath = [ bld.Path('Gems/Cubism3/3rdParty/release/windows/x86_64') ],
        win_performance_libpath = [ bld.Path('Gems/Cubism3/3rdParty/release/windows/x86_64') ],
        win_profile_libpath = [ bld.Path('Gems/Cubism3/3rdParty/release/windows/x86_64') ],

        #linux
        linux_debug_libpath = [ bld.Path('Gems/Cubism3/3rdParty/develop/linux/x86_64') ],
        linux_release_libpath = [ bld.Path('Gems/Cubism3/3rdParty/release/linux/x86_64') ],
        linux_performance_libpath = [ bld.Path('Gems/Cubism3/3rdParty/release/linux/x86_64') ],
        linux_profile_libpath = [ bld.Path('Gems/Cubism3/3rdParty/release/linux/x86_64') ],
        
        #darwin (macosx)
        darwin_debug_libpath = [ bld.Path('Gems/Cubism3/3rdParty/develop/macos') ],
        darwin_release_libpath = [ bld.Path('Gems/Cubism3/3rdParty/release/macos') ],
        darwin_performance_libpath = [ bld.Path('Gems/Cubism3/3rdParty/release/macos') ],
        darwin_profile_libpath = [ bld.Path('Gems/Cubism3/3rdParty/release/macos') ],
        
        #android
        android_debug_libpath = [ bld.Path('Gems/Cubism3/3rdParty/develop/android/armeabi-v7a') ],
        android_release_libpath = [ bld.Path('Gems/Cubism3/3rdParty/release/android/armeabi-v7a') ],
        android_performance_libpath = [ bld.Path('Gems/Cubism3/3rdParty/release/android/armeabi-v7a') ],
        android_profile_libpath = [ bld.Path('Gems/Cubism3/3rdParty/release/android/armeabi-v7a') ],

        #ios
        ios_debug_libpath = [ bld.Path('Gems/Cubism3/3rdParty/develop/ios') ],
        ios_release_libpath = [ bld.Path('Gems/Cubism3/3rdParty/release/ios') ],
        ios_performance_libpath = [ bld.Path('Gems/Cubism3/3rdParty/release/ios') ],
        ios_profile_libpath = [ bld.Path('Gems/Cubism3/3rdParty/release/ios') ],
    )
