

def build(bld):
    bld.DefineGem(
        #includes
        includes = [ bld.Path('Code/CryEngine/CryAction') ],
		
        file_list   = [
			'cubism3.waf_files',
			# uncomment this and set CUBISM3_ANIMATION_FRAMEWORK to 1 in defines to use the Cubism3 Framework
			#'cubism3.animation.framework.waf_files',
		],

        debug_win_linkflags = [ '/VERBOSE' ],

		#defines
		defines = [
			# Sets threading override
			# 0 - no threading
			# 1 - single threading
			# 2 - multithreading
			#'CUBISM3_THREADING=0',

			# Limits the number of sub threads in multi-threaded mode that run at the same time
			#'CUBISM3_MULTITHREAD_LIMITER=4',

			# Enables various debugging options to be usable within the editor
			#'ENABLE_CUBISM3_DEBUG',
			#'ENABLE_CUBISM3_DEBUGLOG',
			#'ENABLE_CUBISM3_THREADLOG',  # Warning! Enabling this will result in console log spam.

			# Sets which animation framework to use
			# 0 - Lumberyard implementation
			# 1 - Live2D Cubism 3 implementation
			#'CUBISM3_ANIMATION_FRAMEWORK=0'
		],

        #library
        lib = [ 'Live2DCubismCore' ],
        
        #library paths
        #windows
        win_debug_libpath = [ bld.Path('Gems/Cubism3/3rdParty/develop/windows/x86_64') ],
        win_release_libpath = [ bld.Path('Gems/Cubism3/3rdParty/release/windows/x86_64') ],
        win_performance_libpath = [ bld.Path('Gems/Cubism3/3rdParty/release/windows/x86_64') ],
        win_profile_libpath = [ bld.Path('Gems/Cubism3/3rdParty/release/windows/x86_64') ],

        #linux
        linux_debug_libpath = [ bld.Path('Gems/Cubism3/3rdParty/develop/linux/x86_64') ],
        linux_release_libpath = [ bld.Path('Gems/Cubism3/3rdParty/release/linux/x86_64') ],
        linux_performance_libpath = [ bld.Path('Gems/Cubism3/3rdParty/release/linux/x86_64') ],
        linux_profile_libpath = [ bld.Path('Gems/Cubism3/3rdParty/release/linux/x86_64') ],
        
        #darwin (macosx)
        darwin_debug_libpath = [ bld.Path('Gems/Cubism3/3rdParty/develop/macos') ],
        darwin_release_libpath = [ bld.Path('Gems/Cubism3/3rdParty/release/macos') ],
        darwin_performance_libpath = [ bld.Path('Gems/Cubism3/3rdParty/release/macos') ],
        darwin_profile_libpath = [ bld.Path('Gems/Cubism3/3rdParty/release/macos') ],
        
        #android
        android_debug_libpath = [ bld.Path('Gems/Cubism3/3rdParty/develop/android/armeabi-v7a') ],
        android_release_libpath = [ bld.Path('Gems/Cubism3/3rdParty/release/android/armeabi-v7a') ],
        android_performance_libpath = [ bld.Path('Gems/Cubism3/3rdParty/release/android/armeabi-v7a') ],
        android_profile_libpath = [ bld.Path('Gems/Cubism3/3rdParty/release/android/armeabi-v7a') ],

        #ios
        ios_debug_libpath = [ bld.Path('Gems/Cubism3/3rdParty/develop/ios') ],
        ios_release_libpath = [ bld.Path('Gems/Cubism3/3rdParty/release/ios') ],
        ios_performance_libpath = [ bld.Path('Gems/Cubism3/3rdParty/release/ios') ],
        ios_profile_libpath = [ bld.Path('Gems/Cubism3/3rdParty/release/ios') ],
    )
